In [62]:
import pandas as pd
import numpy as np

cols = [
    "PTIME", # Target
    "PSTATUS", # most recent patient status (1-dead,0-alive)
    
    # "GTIME_KI", # graft survival
    "NPKID", # num of tx
    # "PREV_TX", # the same organ tx
    # "PREV_TX_ANY", # any previous tx

    # Recipient info
    "AGE",
    'AGE_GROUP',
    'GENDER',
    "ABO",
    "DIAG_KI",
    'ON_DIALYSIS',
    "BMI_CALC",
    "WGT_KG_CALC", # weight
    "HGT_CM_CALC", #"INIT_HGT_CM", # height
    # "LIV_DON_TY", # living donor relation to recipient

    # identification of recipients who passed away
    # "COD_KI", #
    # "COMPOSITE_DEATH_DATE",#
    # "END_DATE",# removal from waiting list
    # "FAILDATE_KI", # kidney fail date
    # "GSTATUS_KI", # graft failed  (1 - yes)

    # 'AMIS', 'BMIS', 'DRMIS', 'HLAMIS' - columns that break everything
    # Donor info
    "AGE_DON",
    'GENDER_DON',
    "ABO_DON",
    "DON_TY",
    "BMI_DON_CALC",
    "WGT_KG_DON_CALC",
    "HGT_CM_DON_CALC",
    # "CREAT_DON",
    # "DIABETES_DON",

    "ABO_MAT",
    # "TX_DATE",

    # "CMV_IGG", "CMV_IGM", "CMV_STATUS",
    # "PRE_TX_TXFUS", # pretransplant transfusions
    # "COLD_ISCH_KI",
    # "WARM_ISCH_TM_DON",
    # 'A1', 'A2', 'B1', 'B2', 'DR1', 'DR2', 'BW4', 'BW6', 'C1', 'C2', 'DR51', 'DR51_2', 'DR52',
    # 'DR52_2', 'DR53', 'DR53_2', 'DQ1', 'DQ2', 'DA1', 'DA2', 'DB1', 'DB2', 'DDR1', 'DDR2', 'RA1',
    # 'RA2', 'RB1', 'RB2', 'RDR1', 'RDR2',
    # "KDPI", "KDRI_MED", 'KDRI_RAO',

    # "WL_ID_CODE", # registration identifier
    # 'DONOR_ID',
    # 'PT_CODE' # recipient id

    ]

dats = pd.read_parquet("/mnt/lustre/helios-home/stadnkyr/Kidney_transplants.parquet", engine='auto', columns=cols)

In [63]:
dats.head()

,PTIME,PSTATUS,NPKID,AGE,AGE_GROUP,GENDER,ABO,DIAG_KI,ON_DIALYSIS,BMI_CALC,WGT_KG_CALC,HGT_CM_CALC,AGE_DON,GENDER_DON,ABO_DON,DON_TY,BMI_DON_CALC,WGT_KG_DON_CALC,HGT_CM_DON_CALC,ABO_MAT
__null_dask_index__,,,,,,,,,,,,,,,,,,,,
1,None,None,None,None,None,M,O,None,N,None,None,None,None,None,None,None,None,None,None,None
2,8754.0,1.0,0.0,38.0,A,M,O,3052.0,N,33.0,101.0,175.0,35.0,M,O,C,23.5134453,74.5,178.0,1.0
3,None,None,None,None,None,F,O,None,N,None,None,None,None,None,None,None,None,None,None,None
4,9966.0,1.0,1.0,43.0,A,F,A,3008.0,N,33.6,103.0,175.0,17.0,F,A1,C,18.1786704,42.0,152.0,1.0
6,None,None,None,None,None,F,O,None,N,None,None,None,None,None,None,None,None,None,None,None

In [64]:
pd.set_option('display.max_columns', None)
display(dats.describe())

,PTIME,PSTATUS,NPKID,AGE,AGE_GROUP,GENDER,ABO,DIAG_KI,ON_DIALYSIS,BMI_CALC,WGT_KG_CALC,HGT_CM_CALC,AGE_DON,GENDER_DON,ABO_DON,DON_TY,BMI_DON_CALC,WGT_KG_DON_CALC,HGT_CM_DON_CALC,ABO_MAT
count,490172,492954,492954,492954,492954,993806,993806,486229,951081,482101,487554,483916,492933,492952,492944,492954,443121,459760,444011,492912
unique,11246,2,6,93,2,2,9,74,2,521,1597,1285,87,2,9,3,70361,1800,779,3
top,3.0,0.0,0.0,56.0,A,M,O,3040.0,Y,26.6,68.0,160.0,47.0,M,O,C,22.1429014,68.0,167.6,1.0
freq,2656,311605,445036,12640,473535,601617,483365,89717,642947,4238,5602,26192,11335,272473,257162,363791,410,8839,23275,443767

# dataframe

In [65]:
df = dats[dats["PSTATUS"].notnull()]
df.shape

(492954, 20)

In [66]:
display(df.head())

,PTIME,PSTATUS,NPKID,AGE,AGE_GROUP,GENDER,ABO,DIAG_KI,ON_DIALYSIS,BMI_CALC,WGT_KG_CALC,HGT_CM_CALC,AGE_DON,GENDER_DON,ABO_DON,DON_TY,BMI_DON_CALC,WGT_KG_DON_CALC,HGT_CM_DON_CALC,ABO_MAT
__null_dask_index__,,,,,,,,,,,,,,,,,,,,
2,8754.0,1.0,0.0,38.0,A,M,O,3052.0,N,33.0,101.0,175.0,35.0,M,O,C,23.5134453,74.5,178.0,1.0
4,9966.0,1.0,1.0,43.0,A,F,A,3008.0,N,33.6,103.0,175.0,17.0,F,A1,C,18.1786704,42.0,152.0,1.0
7,5219.0,0.0,0.0,43.0,A,F,A,3011.0,N,20.1,56.0,167.0,44.0,F,O,L,None,None,None,2.0
9,2206.0,0.0,0.0,9.0,P,F,A,3006.0,N,15.7,23.8,123.0,16.0,F,A1,C,18.9541158,46.7,157.0,1.0
12,5141.0,1.0,0.0,28.0,A,F,O,3011.0,None,23.5,64.0,165.0,16.0,F,O,C,22.9134948,66.2,170.0,1.0

In [67]:
display(df["AGE_GROUP"].value_counts())

A    473535
P     19419
Name: AGE_GROUP, dtype: int64

In [68]:
df['ON_DIALYSIS'].fillna('N', inplace=True) # could be a bad idea
df.dropna(subset=["GENDER_DON", "ABO_DON", "ABO_MAT"], inplace=True)
df.shape

/mnt/lustre/helios-home/stadnkyr/jupyter_virtual_env/lib64/python3.6/site-packages/pandas/core/series.py:4536: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,
/mnt/lustre/helios-home/stadnkyr/jupyter_virtual_env/lib64/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

(492912, 20)

In [69]:
categorical_values = ["AGE_GROUP", "GENDER", "ABO","DON_TY", "ON_DIALYSIS", "GENDER_DON", "ABO_DON", "ABO_MAT"]
numerical_values = ["NPKID", "AGE", "BMI_CALC", "WGT_KG_CALC", "HGT_CM_CALC", "AGE_DON", "BMI_DON_CALC", "WGT_KG_DON_CALC", "HGT_CM_DON_CALC", "PTIME", "PSTATUS"] # "DIAG_KI",

In [70]:
import numpy as np

for column in numerical_values:
    df[column] = df[column].astype(np.float)

/mnt/lustre/helios-home/stadnkyr/jupyter_virtual_env/lib64/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [71]:
for column in categorical_values:
    print(df[column].shape, df[column].dtypes, df[column].isna().sum())

(492912,) object 0
(492912,) object 0
(492912,) object 0
(492912,) object 0
(492912,) object 0
(492912,) object 0
(492912,) object 0
(492912,) object 0

In [72]:
# DONOR HEIGHT
median_adult_men_donor_height = df[df["GENDER_DON"] == "M"]["HGT_CM_DON_CALC"].astype(float).median()
median_adult_women_donor_height = df[df["GENDER_DON"] == "F"]["HGT_CM_DON_CALC"].astype(float).median() 

df.loc[(df['GENDER_DON'] == 'M') & (df['HGT_CM_DON_CALC'].isnull()), 'HGT_CM_DON_CALC'] = median_adult_men_donor_height
df.loc[(df['GENDER_DON'] == 'F') & (df['HGT_CM_DON_CALC'].isnull()), 'HGT_CM_DON_CALC'] = median_adult_women_donor_height

# DONOR WEIGHT
median_adult_men_donor_weight = df[df["GENDER_DON"] == "M"]["WGT_KG_DON_CALC"].astype(float).median()
median_adult_women_donor_weight = df[df["GENDER_DON"] == "F"]["WGT_KG_DON_CALC"].astype(float).median() 

df.loc[(df['GENDER_DON'] == 'M') & (df['WGT_KG_DON_CALC'].isnull()), 'WGT_KG_DON_CALC'] = median_adult_men_donor_weight
df.loc[(df['GENDER_DON'] == 'F') & (df['WGT_KG_DON_CALC'].isnull()), 'WGT_KG_DON_CALC'] = median_adult_women_donor_weight

# DONOR BMI
median_adult_men_donor_bmi = men = df[df["GENDER_DON"] == "M"]["BMI_DON_CALC"].astype(float).median()
median_adult_women_donor_bmi = df[df["GENDER_DON"] == "F"]["BMI_DON_CALC"].astype(float).median() 

df.loc[(df['GENDER_DON'] == 'M') & (df['BMI_DON_CALC'].isnull()), 'BMI_DON_CALC'] = median_adult_men_donor_bmi # COULDDO: calculate individual BMI
df.loc[(df['GENDER_DON'] == 'F') & (df['BMI_DON_CALC'].isnull()), 'BMI_DON_CALC'] = median_adult_women_donor_bmi # COULDDO: calculate individual BMI

/mnt/lustre/helios-home/stadnkyr/jupyter_virtual_env/lib64/python3.6/site-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [73]:
#RECIPIENT HEIGHT
median_adult_men_recipient_height = df[df["GENDER_DON"] == "M"]["HGT_CM_DON_CALC"].astype(float).median()
median_adult_women_recipient_height = df[df["GENDER_DON"] == "F"]["HGT_CM_DON_CALC"].astype(float).median() 

df.loc[(df['GENDER'] == 'M') & (df['HGT_CM_CALC'].isnull()) & (df['AGE_GROUP'] == 'A'), 'HGT_CM_CALC'] = median_adult_men_recipient_height
df.loc[(df['GENDER'] == 'F') & (df['HGT_CM_CALC'].isnull()) & (df['AGE_GROUP'] == 'A'), 'HGT_CM_CALC'] = median_adult_women_recipient_height

# RECIPIENT WEIGHT
median_adult_men_recipient_weight = df[df["GENDER_DON"] == "M"]["WGT_KG_DON_CALC"].astype(float).median()
median_adult_women_recipient_weight = df[df["GENDER_DON"] == "F"]["WGT_KG_DON_CALC"].astype(float).median() 

df.loc[(df['GENDER'] == 'M') & (df['WGT_KG_CALC'].isnull()) & (df['AGE_GROUP'] == 'A'), 'WGT_KG_CALC'] = median_adult_men_recipient_weight
df.loc[(df['GENDER'] == 'F') & (df['WGT_KG_CALC'].isnull()) & (df['AGE_GROUP'] == 'A'), 'WGT_KG_CALC'] = median_adult_women_recipient_weight

# RECIPIENT BMI
median_adult_men_recipient_bmi = men = df[df["GENDER_DON"] == "M"]["BMI_DON_CALC"].astype(float).median()
median_adult_women_recipient_bmi = df[df["GENDER_DON"] == "F"]["BMI_DON_CALC"].astype(float).median() 

df.loc[(df['GENDER'] == 'M') & (df['BMI_CALC'].isnull()) & (df['AGE_GROUP'] == 'A'), 'BMI_CALC'] = median_adult_men_recipient_bmi # COULDDO: calculate individual BMI
df.loc[(df['GENDER'] == 'F') & (df['BMI_CALC'].isnull()) & (df['AGE_GROUP'] == 'A'), 'BMI_CALC'] = median_adult_women_recipient_bmi # COULDDO: calculate individual BMI

df.dropna(subset=["BMI_CALC", "WGT_KG_CALC", "HGT_CM_CALC", "AGE_DON", "PTIME"], inplace=True)

/mnt/lustre/helios-home/stadnkyr/jupyter_virtual_env/lib64/python3.6/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [74]:
df.shape

(489523, 20)

In [75]:
# for column in categorical_columns:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.reset_index()
df.head()

/mnt/lustre/helios-home/stadnkyr/jupyter_virtual_env/lib64/python3.6/site-packages/pandas/core/frame.py:4389: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

,PTIME,PSTATUS,NPKID,AGE,AGE_GROUP,GENDER,ABO,DIAG_KI,ON_DIALYSIS,BMI_CALC,WGT_KG_CALC,HGT_CM_CALC,AGE_DON,GENDER_DON,ABO_DON,DON_TY,BMI_DON_CALC,WGT_KG_DON_CALC,HGT_CM_DON_CALC,ABO_MAT
__null_dask_index__,,,,,,,,,,,,,,,,,,,,
2,8754.0,1.0,0.0,38.0,A,M,O,3052.0,N,33.0,101.0,175.0,35.0,M,O,C,23.513445,74.5,178.0,1.0
4,9966.0,1.0,1.0,43.0,A,F,A,3008.0,N,33.6,103.0,175.0,17.0,F,A1,C,18.178670,42.0,152.0,1.0
7,5219.0,0.0,0.0,43.0,A,F,A,3011.0,N,20.1,56.0,167.0,44.0,F,O,L,26.055697,69.9,163.0,2.0
9,2206.0,0.0,0.0,9.0,P,F,A,3006.0,N,15.7,23.8,123.0,16.0,F,A1,C,18.954116,46.7,157.0,1.0
12,5141.0,1.0,0.0,28.0,A,F,O,3011.0,N,23.5,64.0,165.0,16.0,F,O,C,22.913495,66.2,170.0,1.0

In [76]:
for column in numerical_values:
    print(column, df[column].shape, df[column].dtypes, df[column].isna().sum())

NPKID (489523,) float64 0
AGE (489523,) float64 0
BMI_CALC (489523,) float64 0
WGT_KG_CALC (489523,) float64 0
HGT_CM_CALC (489523,) float64 0
AGE_DON (489523,) float64 0
BMI_DON_CALC (489523,) float64 0
WGT_KG_DON_CALC (489523,) float64 0
HGT_CM_DON_CALC (489523,) float64 0
PTIME (489523,) float64 0
PSTATUS (489523,) float64 0

In [82]:
import numpy as np

# construct Y
from sksurv.util import Surv

survival_time = df['PTIME'].astype(np.float64)
event = df['PSTATUS'].astype(float).astype(np.bool)

# numerical_values.remove('PTIME')
# numerical_values.remove('PSTATUS')
df['PSTATUS'] = df['PSTATUS'].astype(bool)

# df.head()

y = Surv.from_dataframe('PSTATUS', 'PTIME', df)
y

/mnt/lustre/helios-home/stadnkyr/jupyter_virtual_env/lib64/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

array([( True, 8754.), ( True, 9966.), (False, 5219.), ...,
       ( True, 1372.), (False, 1845.), (False, 1826.)],
      dtype=[('PSTATUS', '?'), ('PTIME', '<f8')])

In [83]:
y_oth = df

In [84]:

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

from sksurv.preprocessing import OneHotEncoder
from sksurv.column import encode_categorical
from sksurv.column import standardize

data_x = encode_categorical(df, categorical_values)

In [85]:
categorical = df[categorical_values]
numerical = df[numerical_values]

numerical_x = standardize(numerical)
categorical_x = encode_categorical(categorical)

df_prep = pd.concat([numerical_x, categorical_x], axis=1)
# df_prep = df_prep.drop(['PTIME', 'PSTATUS'], axis=1)

df_prep

,NPKID,AGE,BMI_CALC,WGT_KG_CALC,HGT_CM_CALC,AGE_DON,BMI_DON_CALC,WGT_KG_DON_CALC,HGT_CM_DON_CALC,PTIME,PSTATUS,AGE_GROUP=P,GENDER=M,ABO=A1,ABO=A1B,ABO=A2,ABO=A2B,ABO=AB,ABO=B,ABO=O,DON_TY=F,DON_TY=L,ON_DIALYSIS=Y,GENDER_DON=M,ABO_DON=A1,ABO_DON=A1B,ABO_DON=A2,ABO_DON=A2B,ABO_DON=AB,ABO_DON=B,ABO_DON=O,ABO_MAT=2.0,ABO_MAT=3.0
__null_dask_index__,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,-0.312928,-0.669799,1.062817,1.105770,0.433657,-0.190119,-0.553425,-0.139291,0.565165,2.856017,True,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,2.616722,-0.344701,1.170284,1.202712,0.433657,-1.352273,-1.454756,-1.639981,-1.101071,3.418428,True,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,-0.312928,-0.344701,-1.247716,-1.075428,-0.145991,0.390959,-0.123902,-0.351697,-0.396125,1.215651,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
9,-0.312928,-2.555368,-2.035805,-2.636196,-3.334055,-1.416837,-1.323741,-1.422958,-0.780641,-0.182488,False,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,-0.312928,-1.319995,-0.638738,-0.687659,-0.290903,-1.416837,-0.654789,-0.522544,0.052477,1.179456,True,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,-0.312928,0.955691,-0.817850,-0.348362,0.636534,1.617677,-0.168729,-0.624129,-0.748598,-0.362998,False,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
542,-0.312928,1.475848,1.367306,1.837683,1.006060,1.617677,0.113673,-0.227024,-0.421759,-0.392232,False,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
545,-0.312928,1.215770,1.313573,2.269076,1.556725,0.842908,0.139500,0.567188,0.712563,-0.569494,True,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
546,-0.312928,1.475848,-0.244694,-0.295044,-0.102517,0.261830,-0.026795,-0.125439,-0.101329,-0.350005,False,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
547,-0.312928,1.150750,1.367306,2.147898,1.375585,2.005062,-0.434287,-0.143909,0.392133,-0.358822,False,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [86]:
import numpy as np

# construct Y
from sksurv.util import Surv

survival_time = data_x['PTIME'].astype(np.float64)
event = data_x['PSTATUS'].astype(float).astype(np.bool)

y = Surv.from_arrays(event, survival_time, "Status", "Days")
data_x = data_x.drop(['PTIME', 'PSTATUS'], axis=1)

In [87]:
# data_x.head()
data_x.shape

(489523, 32)

In [88]:
# df_prepared_small = data_x[:10000]
df_prepared_small = df_prep[:10000]
y_small = y[:10000]

df_prepared_small

,NPKID,AGE,BMI_CALC,WGT_KG_CALC,HGT_CM_CALC,AGE_DON,BMI_DON_CALC,WGT_KG_DON_CALC,HGT_CM_DON_CALC,PTIME,PSTATUS,AGE_GROUP=P,GENDER=M,ABO=A1,ABO=A1B,ABO=A2,ABO=A2B,ABO=AB,ABO=B,ABO=O,DON_TY=F,DON_TY=L,ON_DIALYSIS=Y,GENDER_DON=M,ABO_DON=A1,ABO_DON=A1B,ABO_DON=A2,ABO_DON=A2B,ABO_DON=AB,ABO_DON=B,ABO_DON=O,ABO_MAT=2.0,ABO_MAT=3.0
__null_dask_index__,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2,-0.312928,-0.669799,1.062817,1.105770,0.433657,-0.190119,-0.553425,-0.139291,0.565165,2.856017,True,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,2.616722,-0.344701,1.170284,1.202712,0.433657,-1.352273,-1.454756,-1.639981,-1.101071,3.418428,True,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,-0.312928,-0.344701,-1.247716,-1.075428,-0.145991,0.390959,-0.123902,-0.351697,-0.396125,1.215651,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
9,-0.312928,-2.555368,-2.035805,-2.636196,-3.334055,-1.416837,-1.323741,-1.422958,-0.780641,-0.182488,False,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,-0.312928,-1.319995,-0.638738,-0.687659,-0.290903,-1.416837,-0.654789,-0.522544,0.052477,1.179456,True,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28,2.616722,-0.149642,-1.928338,-1.569833,-0.102517,-0.319247,-0.156203,-0.208554,-0.075695,-0.349077,False,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
31,-0.312928,0.175456,1.618061,2.724704,1.737865,0.778344,0.546136,-0.162379,-0.780641,-1.126801,False,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
35,-0.312928,-0.409721,0.668773,1.057299,0.817674,0.197266,1.260172,1.153611,0.244735,-1.010792,True,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
38,-0.312928,0.695613,1.546417,1.066993,-0.102517,-0.771196,-0.526763,-0.116204,0.565165,-0.372743,False,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
41,-0.312928,0.695613,-1.319361,-1.128746,-0.145991,1.617677,0.389441,-0.010001,-0.396125,-1.203366,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [89]:
# np.isnan(y_small['']).any()
print(np.any(np.isnan(y_small['Status'])))
print(np.all(np.isfinite(y_small['Status'])))

print(np.any(np.isnan(y_small['Days'])))
print(np.all(np.isfinite(y_small['Days'])))

False
True
False
True

In [91]:
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis

# neco = standardize(df_prepared_small)

cox_ph = CoxnetSurvivalAnalysis()
cox_ph.fit(df_prepared_small, y_small)

/mnt/lustre/helios-home/stadnkyr/jupyter_virtual_env/lib64/python3.6/site-packages/ipykernel_launcher.py:6: ConvergenceWarning: Optimization terminated early, you might want to increase the number of iterations (max_iter=100000).

CoxnetSurvivalAnalysis()